ALTER TABLE raw_events ADD COLUMN IF NOT EXISTS analytics_consent BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE raw_events ADD COLUMN IF NOT EXISTS personalization_consent BOOLEAN NOT NULL DEFAULT TRUE;
