package com.aurora.objectives;

public enum WorkflowStage {
  OBJECTIVE_DEFINITION,
  INSIGHT_GENERATION,
  EXPERIMENT_DESIGN,
  SIGNAL_MODEL_IMPLEMENTATION,
  APPROVAL,
  EXPERIMENT_CONFIGURATION,
  DEPLOYMENT,
  MEASUREMENT,
  ANALYSIS
}
